# behavior.py
from .autonomous_behavior import AutonomousBehavior
from .controllable_behavior import ControllableBehavior
from .behavior_config import BehaviorConfig


class Behavior:
    """
    The Behavior class manages agent behavior within the gym environment.
    
    This class provides a unified interface for both autonomous and controllable
    agent behaviors. It requires a gym environment for initialization and must
    be fully configured using the init_from_profile method with a behavior profile.
    
    Args:
        gym: The gym environment where the agent operates.
    """
    def __init__(self, gym):
        self.config = BehaviorConfig()
        self.config.register_callback(self._on_config_change)
        self.autonomous = AutonomousBehavior(gym, self.config)
        self.controllable = ControllableBehavior(gym, self.config)
    
    def init_from_profile(self, raw_profile):
        """
        Initialize the behavior from a profile.

        Args:
            raw_profile (dict): The profile of the behavior. The profile is a dictionary that contains the configuration of the behavior. 
            
        Supported keys in the raw_profile:
            - velocity_mean: The mean of the velocity distribution.
            - velocity_sd: The standard deviation of the velocity distribution.
            - random_drift_magnitude: The magnitude of the random drift.
            - switch_direction_prob: The probability of switching the direction.
            - switch_velocity_prob: The probability of switching the velocity.
            - max_velocity: The maximum velocity of the agent.
            - avoid_boundary_dist: The distance from the boundary to avoid.
            - pause_prob: The probability of pausing the agent.
        """
        self.autonomous.init_from_profile(raw_profile)
        self.controllable.init_from_profile(raw_profile)
    
    def _on_arena_change(self):
        self.autonomous._recompute_maps()
        self.controllable._recompute_maps()
    
    def generate_trajectory(self, duration: float, batch_size: int, init_pos=None, init_state=None):
        """
        Generate a trajectory and return the generated data.

        Args:
            duration (float): Duration of the trial in seconds.
            batch_size (int): Number of trials to generate.
            init_pos (np.ndarray, optional): Initial position of the agent. 
                If both init_pos and init_state are provided, init_pos will be used.
            init_state (AgentState, optional): Initial state of the agent. 
                This is a more complex version of init_pos that contains not only 
                the initial position but also the last displacement. This state 
                should be an `AgentState` object generated by the `generate_trajectory` function.
                If both init_pos and init_state are provided, init_state will be used.
                If neither is provided, the agent will be spawned at a random position.

        Returns:
            tuple: A tuple containing:
                - generated_trajectory (Trajectory): Generated trajectory as a rtgym.dataclass.Trajectory object.
                - last_state (AgentState): The last state of the agent.
        """
        return self.autonomous.generate_trajectory(duration, batch_size, init_pos, init_state)

    def _on_config_change(self, attr, value):
        if attr == "avoid_boundary_dist":
            self._on_arena_change()
