from .rectangle import *
from .circle import *
from .triangle import *
from .two_rooms import *
from .cornered_rectangle import *
from .maze_0 import *
from .maze_1 import *
from .maze_2 import *
from .trainer_0 import *
